### ISSUE TITLE
Fortnite replay reader

### ISSUE THREAD

**Issue by fredimachado** [tfausak/storm#1]
Hey Taylor!

I'm writing a Fortnite replay reader and I think it might be interesting to you: https://github.com/fredimachado/FortniteReplayReader

Sorry about creating an issue, but I didn't know how to contact you.

**Comment by tfausak** [comment]
Cool, thanks for the heads up! Looks like you've made it a bit further than me 😄

**Comment by fredimachado** [comment]
Yeah, I was really interested in reading the file, and I had some spare time to do some investigation and live stream the process of writing the code. I'm going to do some more investigation though and I'll update the code, so you can watch or star it on Github if you want.

Oh, and you can do whatever you want with my code, since it's using MIT license.

Cheers!
